In [5]:
import numpy as np

A = np.array([i for i in range(6)])
B = np.array([[j for k in range(2)] for j in range(4)])

print(A)
print(B)

np.random.shuffle(A)
np.random.shuffle(B)

print()
print(A)
print(B)

[0 1 2 3 4 5]
[[0 0]
 [1 1]
 [2 2]
 [3 3]]

[1 5 3 0 4 2]
[[0 0]
 [3 3]
 [1 1]
 [2 2]]


In [1]:
'W{}'.format(1) = 1
print(W1)

SyntaxError: can't assign to function call (<ipython-input-1-6e5203c7f6f2>, line 1)

In [57]:
X = np.array([2, 4, 6, 8])

print("np.max(X) ==", np.max(X))
print("np.min(X) ==", np.min(X))
print("np.argmax(X) ==", np.argmax(X))
print("np.argmin(X) ==", np.argmin(X))

print("np.sum(X) ==", np.sum(X))
print("np.exp(X) ==", np.exp(X))
print("np.log(X) ==", np.log(X))

Y = np.array([[2, 4, 6], [1, 2, 3], [0, 5, 8]])

print("np.max(Y) ==", np.max(Y, axis=0))
print("np.min(Y) ==", np.min(Y, axis=0))

print("np.max(Y) ==", np.max(Y, axis=1))
print("np.min(Y) ==", np.min(Y, axis=1))

print("np.argmax(Y) ==", np.argmax(Y, axis=0))
print("np.argmin(Y) ==", np.argmin(Y, axis=0))

print("np.argmax(Y) ==", np.argmax(Y, axis=1))
print("np.argmin(Y) ==", np.argmin(Y, axis=1))

np.max(X) == 8
np.min(X) == 2
np.argmax(X) == 3
np.argmin(X) == 0
np.sum(X) == 20
np.exp(X) == [   7.3890561    54.59815003  403.42879349 2980.95798704]
np.log(X) == [0.69314718 1.38629436 1.79175947 2.07944154]
np.max(Y) == [2 5 8]
np.min(Y) == [0 2 3]
np.max(Y) == [6 3 8]
np.min(Y) == [2 1 0]
np.argmax(Y) == [0 2 2]
np.argmin(Y) == [2 1 1]
np.argmax(Y) == [2 2 2]
np.argmin(Y) == [0 0 0]


In [51]:
balance = 350000
spend = 22990 + 28590 + 42200 + 37700 + 28590 + 8500 + 21600 + 27195 + 108992

print(balance - spend)

23643


In [41]:
def calc(list_data):
    sum = 0
    
    try:
        sum = list_data[0] + list_data[1] + list_data[2]
        
        if sum < 0:
            raise Exception("Sum in minus")
            
    except IndexError as err:
        print(str(err))
    except Exception as err:
        print(str(err))
    finally:
        print(sum)
        
calc([1, 2])
calc([1, 2, -100])

list index out of range
0
Sum in minus
-97


In [26]:
def print_name(name):
    print("[def] ", name)
    
class SameTest:
    def __init__(self):
        pass
    
    def print_name(self, name):
        print("[SameTest] ", name)
        
    def call_test(self):
        print_name("KIM")
        self.print_name("KIM")
        
obj = SameTest()
print_name("LEE")
obj.print_name("LEE")
obj.call_test()

[def]  LEE
[SameTest]  LEE
[def]  KIM
[SameTest]  KIM


In [25]:
class PrivateMemberTest:
    def __init__(self, name1, name2):
        self.name1 = name1
        self.__name2 = name2
        print("initialized with " + name1 + " ," + name2)
        
    def getNames(self):
        self.__printNames()
        return self.name1, self.__name2
    
    def __printNames(self):
        print(self.name1, self.__name2)
        
obj = PrivateMemberTest("PARK", "KIM")

print(obj.name1)
print(obj.getNames())
print(obj.__printNames())
print(obj.__name2)

initialized with PARK ,KIM
PARK
PARK KIM
('PARK', 'KIM')


AttributeError: 'PrivateMemberTest' object has no attribute '__printNames'

# 데이터타입

## 예제 1.

In [10]:
print("John's House")

John's House


## 예제 2.

- \n: 줄 바꾸기 기능
- \t: tap과 같이 들여쓰기 기능

## 예제 3.

In [18]:
license_plate = "24가 2210"
print(license_plate[-4:])

2210


## 예제 4.

In [1]:
list_A = [1, 2, 3, 4, 5]
a = len(list_A)
print(a)

5


In [1]:
list_B = [1, 2, 3]
b = len(list_B)
print(b)

3


Error 원인: 위에서 len에 5를 할당해버림으로써 len이 기존 함수 기능이 아닌 5를 담은 변수가 됨

해결방법 : 다른 변수에 len(list_A)를 할당하기

## 예제 5.

In [3]:
str = 'Hello'
str[0] = 'K'
print(str)

TypeError: 'str' object does not support item assignment

예상 결과: 'Hello' 출력 (X) <br>

결과: str 자료형은 읽기 전용이므로 이미 2번 코드에서 에러 발생

## 예제 6.

In [40]:
string = "Hello/Machine/Deep/Learning"
print(string)

list_A = [string[:5], string[6:13], string[14:18], string[19:]]
print(list_A)

list_B = []
# list_B = list_B.append(string[:5]).append(string[6:13]).append(string[14:18]).append(string[19:])
# append를 이렇게 연속으로 하면 안되는 구나... -> 특정 반환값을 가진 메소드끼리만 체이닝 가능

list_C = string.split('/')
print(list_C)

Hello/Machine/Deep/Learning
['Hello', 'Machine', 'Deep', 'Learning']
['Hello', 'Machine', 'Deep', 'Learning']


## 예제 7.

In [17]:
A = 'hello world'
A_1 = A[:1]
A_2 = A[-5:]
A = A_1 + 'i' + ' ' + A_2
print(A)

hi world


## 예제 8.

In [23]:
str = "AB,CDE:FG,WX,Y".split(',')
print(str, str[-2], str[0][:-1], str[2:], str[:][:], sep='\n')

['AB', 'CDE:FG', 'WX', 'Y']
WX
A
['WX', 'Y']
['AB', 'CDE:FG', 'WX', 'Y']


```python
str = ['AB', 'CDE:FG', 'WX', 'Y']
str[-2] = 'WX'
str[0][:-1] = 'AB'
str[2:] = ['WX'. 'Y']
str = ['AB', 'CDE:FG', 'WX', 'Y']
```

## 예제 9.

In [27]:
files = 'tmp/cat.0.jpg:python.1.py:temp/hello.6316.txt:text.6331.docx'

new_var = [files.split(':')[2].split('.')[1].strip()]
print(new_var)

['6316']


```python
'temp/hello.6316.txt'
'6316'

'6316'
```

## 예제 10.

In [52]:
import glob
import random

all_files = glob.glob('train/*')
print(all_files)

temp = []
data = []

for file in all_files:
    start = file.find('\\') + 1
    end = file.find('.')
    temp.append(file[start:end])
    print(start, end)
    print(data)
    if 'dog' in file or 'cat' in file:
        temp.

['train\\Agent.py', 'train\\cat.6.jpg', 'train\\cat.9.jpg', 'train\\dog.6316.jpg', 'train\\dog.6331.jpg', 'train\\hello.txt']
6 11
['Agent']
6 9
['Agent', 'cat']
6 9
['Agent', 'cat', 'cat']
6 9
['Agent', 'cat', 'cat', 'dog']
6 9
['Agent', 'cat', 'cat', 'dog', 'dog']
6 11
['Agent', 'cat', 'cat', 'dog', 'dog', 'hello']


# if, for, 리스트 컴프리핸션

## 예제 1.

In [53]:
for _ in range(6):
    print('*', end='')

******

## 예제 2.

In [56]:
for j in range(5):
    print(('*' * (5 - j)) + (' ' * j))

*****
**** 
***  
**   
*    


## 예제 3.

In [5]:
apart = [[101, 102, 103, 104], [201, 202, 203, 204], [301, 302, 303, 304], [401, 402, 403, 404]]
arrears = [101, 203, 301, 404]

for col in range(len(apart)):
    for row in range(len(apart[col])):
        if apart[col][row] in arrears:
            pass
        else:
            print(apart[col][row], end=' ')

102 103 104 201 202 204 302 303 304 401 402 403 

## 예제 4.

In [7]:
even_number = [i for i in range(10) if i % 2 == 0]
print(even_number)

[0, 2, 4, 6, 8]


## 예제 5.

In [8]:
my_list = ['A', 'B', 'C', 'D']

for data in my_list:
    if data == 'A':
        pass
    else:
        print(data, end=' ')

B C D 

## 예제 6.

In [10]:
my_list = [3, 1, 7, 12, 5, 16]

for data in my_list:
    if data % 3 == 0 or data % 4 == 0:
        print(data, end=' ')
    else:
        pass

3 12 16 

## 예제 7.

In [14]:
test_data = [[10, 20, 30], [1, 2, 3], [100, 200, 300]]

xdata = [x[1:-1] for x in test_data]
tdata = [[x[0], x[-2]] for x in test_data]

print(xdata, tdata, sep='\n')

[[20], [2], [200]]
[[10, 20], [1, 2], [100, 200]]


```python
xdata = [20, 2, 200] # 리스트를 슬라이싱하면 리스트가 나옴
tdata = [[10, 20], [1, 2], [100, 200]]
```

## 예제 8.

In [46]:
import glob

all_files = glob.glob('test_dir1/*')
print(all_files)

data = [file[file.find('\\') + 1:file.find('.')] for file in all_files if 'dog' in file or 'cat' in file]
data = list(set(data))

for i in data:
    print(i, end=' ')

['test_dir1\\cat.6.jpg', 'test_dir1\\cat.9.jpg', 'test_dir1\\dog.6316.jpg', 'test_dir1\\dog.6331.jpg']
cat dog 

## 예제 9.

In [68]:
import glob

all_files = glob.glob('test_dir2/*')
data = [file.split('.')[1].strip() for file in all_files]
data = list(set(data))

for i in data:
    print(i, end=' ')

deer rabbit cat dog 

## 예제 10.

In [78]:
import glob

all_files = glob.glob('test_dir3/*')
data = [file[10:] for index, file in enumerate(all_files) if 'dog' in file]
print(data)

['dog.1.png', 'dog.6316.jpg', 'dog.6331.jpg']


## 예제 11.

In [82]:
import glob

dir1_files = glob.glob('test_dir1/*')
dir2_files = glob.glob('test_dir3/*')

data_dir1 = [file[10:] for file in dir1_files]
data_dir2 = [file[10:] for file in dir2_files]

In [83]:
def print_name(name='T', count=2):
    for i in range(count):
        print("name = ", name)
        
print_name()

name =  T
name =  T


# 함수

## 예제 1.

In [3]:
def add_start_to_end(start, end):
    total = 0
    for i in range(start, end + 1):
        total += i
        
    return total

print(add_start_to_end(10, 20))

165


## 예제 2.

In [5]:
def get_abbr(input_list):
    output_list = []
    for element in input_list:
        output_list.append(element[:3])
        
    return output_list

city = ['Seoul', 'Daegu', 'Kwangju', 'Jeju']
print(get_abbr(city))

['Seo', 'Dae', 'Kwa', 'Jej']


## 예제 3.

In [7]:
def square(x):
    return x ** 2

f = lambda x: square(x)

print(square(2))
print(f(2))

4
4


## 예제 4.

In [9]:
hello()

def hello():
    print("Hi")

NameError: name 'hello' is not defined

Error 원인: 함수를 정의하기 전에 함수를 호출<br>
해결방안: 함수를 호출하기 전에 함수를 정의

## 예제 5.

In [11]:
def message():
    print("A")
    print("B")
    
message()

print("C")

message()

A
B
C
A
B


```python
A
B
C
A
B
```

## 예제 6.

In [13]:
def func(var):
    x1 = var[0]
    x2 = var[1]
    
    return (x1 + x2) / 2

def test_func(f, W):
    ret_val_list = []
    W[0] = W[0] + 0.1 # W[0] = 1.1
    ret_val = f(W) # 1.1 + 2.0 / 2 = 1.55
    ret_val_list.append(ret_val) # ret_val_list = [1.55]
    W[1] = W[1] - 0.1 # W[1] = 1.9
    ret_val = f(W) # 1.1 + 1.9 / 2 = 1.5
    ret_val_list.append(ret_val) # ret_val_list = [1.55, 1.5]
    return ret_val_list

f = lambda x : func(x)

ret_val = test_func(f, [1.0, 2.0]) # [1.55, 1.5]
print(ret_val)

[1.55, 1.5]


# 클래스, 예외, with

## 예제 2.

In [41]:
class Point:
    def __init__(self, x, y):
        self.x = x
        self.y = y
        
    def setx(self, x):
        self.x = x
        
    def sety(self, y):
        self.y = y
        
    def get(self):
        return self.x, self.y
    
    def move(self, dx, dy):
        self.x += dx
        self.y += dy
        
p = Point(1, 1)
p.setx(2)
p.sety(2)
print(p.get())

(2, 2)


## 예제 3.

In [42]:
class MyTest:
    def hello():
        print("MyTest hello method")
        
obj = MyTest()
obj.hello()

TypeError: hello() takes 0 positional arguments but 1 was given

Error 원인: 메소드에 self 매개변수가 없음<br>
해결방안: 메소드에 self를 추가해준다

## 예제 4.

In [43]:
class MyCalc:
    def __init__(self, a, b):
        self.a = a
        self.b = b
        
    def summation(self):
        return self.a + self.b
    
    def subtract(self):
        return self.a - self.b
    
    def multiply(self):
        return self.a * self.b
    
    def divide(self):
        return self.a / self.b
    
obj = MyCalc(1,1)
obj.summation()

2

## 예제 5.

In [50]:
class MyFile:
    def __init__(self):
        pass
        
    def save_file(self, array):
        try:
            with open('text_file.txt', 'w') as file:
                file.write(array)
        except Exception as err:
            print(str(err))
            
obj = MyFile()
obj.save_file('Hello, world!')

# 넘파이

## 예제 1-1.

In [27]:
A = np.array([1, 2])
B = np.array([3, 4])
T = np.array([5, 6])

print((1 - A) * A)
print(T * (1 - A))

[ 0 -2]
[ 0 -6]


## 예제 1-2.

In [28]:
C = np.array([[2, 3]])
D = np.array([[4, 5]])
T = np.array([[7, 8]])

print((1 - C) * C)
print(T * (1 - C) * C)

[[-2 -6]]
[[-14 -48]]


## 예제 1-3.

In [34]:
X = np.array([[1, 2], [3, 4]])
W = np.array([[0, 1, 1], [3, 2, 1]])
T = np.array([[1, 0], [0, 2]])

b = -1

Y = np.dot(X, W) + b
E = T - Y

ValueError: operands could not be broadcast together with shapes (2,2) (2,3) 

Error 원인: X, W의 열이 맞지 않음

## 예제 1-4.

In [33]:
A = np.array([[1, 2, 3], [4, 5, 6]])
B = np.array([10, 20, 30])
C = A.T
D = np.dot(C, B)

ValueError: shapes (3,2) and (3,) not aligned: 2 (dim 1) != 3 (dim 0)

Error 원인: 행렬과 행렬 아닌 벡터끼리 행렬곱을 할 수 없음.

## 예제 2-1.

In [63]:
def func1(var):
    for col in range(var.shape[0]):
        for row in range(var.shape[1]):
            print("value =", var[col, row])
            
def func2(var):
    it = np.nditer(var, flags=['multi_index'], op_flags=['readwrite'])
    
    while not it.finished:
        idx = it.multi_index
        print("value =", var[idx])
        it.iternext()
            
var = np.array([[2, 4], [1, 2], [0, 5]])
func1(var)
print()
func2(var)

value = 2
value = 4
value = 1
value = 2
value = 0
value = 5

value = 2
value = 4
value = 1
value = 2
value = 0
value = 5


## 예제 2-2.

In [68]:
X = np.array([[7, 5, 3, 1], [1, 2, 3, 4], [4, 0, 2, 8]])

A = X.reshape(-1, 3)
B = A[0:2, 1:2]
C = A[1:, :-1]
D = np.argmax(A, 1)
E = C.reshape(-1, 6)
F = np.sum(E)
G = np.log(X)

print(A, B, C, D, E, F, G, sep='\n\n')

[[7 5 3]
 [1 1 2]
 [3 4 4]
 [0 2 8]]

[[5]
 [1]]

[[1 1]
 [3 4]
 [0 2]]

[0 2 1 2]

[[1 1 3 4 0 2]]

11

[[1.94591015 1.60943791 1.09861229 0.        ]
 [0.         0.69314718 1.09861229 1.38629436]
 [1.38629436       -inf 0.69314718 2.07944154]]


C:\Users\leeye\anaconda3\lib\site-packages\ipykernel_launcher.py:9: RuntimeWarning: divide by zero encountered in log
  if __name__ == '__main__':


```python
[[7, 5, 3],
 [1, 1, 2],
 [3, 4, 4],
 [0, 2, 8]]

[[5],
 [1]]

[[1, 1],
 [3, 4],
 [0, 2]]

axis 없음 -> Error

원소가 2개인데 열이 6개인 행렬을 만들 수 없음 -> Error

E가 Error -> Error
```

## 예제 2-3.

In [74]:
def loss_func(xdata, tdata):
    W = np.array([[np.random.rand(1, 1)]])
    b = np.array([np.random.rand(1)])
    
    y = np.dot(xdata, W) + b
    
    nth_term = (tdata - y) ** 2
    
    it = np.nditer(nth_term, flags=['multi_index'], op_flags=['readwrite'])
    
    total = 0
    
    while not it.finished:
        idx = it.multi_index
        total += nth_term[idx]
        it.iternext()
        
    loss = total / 5
    
    return loss

xdata = np.array([1, 2, 3, 4, 5]).reshape(5, 1)
tdata = np.array([3, 4, 5, 6, 7]).reshape(5, 1)

loss_func(xdata, tdata)

40.125392747587014

In [75]:
def loss_func(xdata, tdata):
    W = np.array([[np.random.rand(1, 1)]])
    b = np.array([np.random.rand(1)])
    
    y = np.dot(xdata, W) + b
    
    loss = np.sum((tdata - y) ** 2) / len(xdata)
    
    return loss

xdata = np.array([1, 2, 3, 4, 5]).reshape(5, 1)
tdata = np.array([3, 4, 5, 6, 7]).reshape(5, 1)

loss_func(xdata, tdata)

106.04919316056309

# 수치미분

## 예제 1-1.

In [15]:
import numpy as np

def func2(x):
    return 3*x*np.exp(x)

f = lambda x : func2(x)

def numerical_derivative2(f, x):
    delta_x = 1e-4
    
    return (f(x + delta_x) - f(x - delta_x)) / (2*delta_x)

x = 2.0

print(numerical_derivative2(f, x))
print(3*np.exp(2.0) + 3*2.0*np.exp(2.0))

66.50150507518049
66.50150489037586


## 편미분 코드

In [38]:
import numpy as np

def numerical_derivative(f, x):
    delta_x = 1e-4
    grad = np.zeros_like(x)
    
    print('debug 1. initial input variable = ', x)
    print('debug 2. initial grad = ', grad)
    print('========================================')
    
    it = np.nditer(x, flags=['multi_index'], op_flags=['readwrite'])
    
    while not it.finished:
        idx = it.multi_index
        
        print('debug 3. idx = ', idx, ', x[idx] = ', x[idx])
        
        tmp_val = x[idx]
        x[idx] = float(tmp_val) + delta_x
        fx1 = f(x) # f(x + delta_x)
        
        x[idx] = float(tmp_val) - delta_x
        fx2 = f(x) # f(x - delta_x)
        grad[idx] = (fx1 - fx2) / (2*delta_x)
        
        print('debug 4. grad[idx] = ', grad[idx])
        print('debug 5. grad = ', grad)
        print('=======================================')
        
        x[idx] = tmp_val
        it.iternext()
        
    return grad

## 예제 2-1.

In [39]:
def func1(W):
    x = W
    return x**2

f = lambda W : func1(W)

W = np.array([3.0])

ret = numerical_derivative(f, W)
print('type(ret) = ', type(ret), ', ret_val = ', ret)

debug 1. initial input variable =  [3.]
debug 2. initial grad =  [0.]
debug 3. idx =  (0,) , x[idx] =  3.0
debug 4. grad[idx] =  6.000000000012662
debug 5. grad =  [6.]
type(ret) =  <class 'numpy.ndarray'> , ret_val =  [6.]


## 예제 2-2.

In [42]:
def func2(x, y):
    return 2*x + 3*x*y + y**3

f = lambda W : func2(W[0], W[1])

W = np.array([1.0, 2.0])

ret = numerical_derivative(f, W)
print('type(ret) = ', type(ret), ', ret_val = ', ret)

debug 1. initial input variable =  [1. 2.]
debug 2. initial grad =  [0. 0.]
debug 3. idx =  (0,) , x[idx] =  1.0
debug 4. grad[idx] =  7.999999999990237
debug 5. grad =  [8. 0.]
debug 3. idx =  (1,) , x[idx] =  2.0
debug 4. grad[idx] =  15.000000010019221
debug 5. grad =  [ 8.         15.00000001]
type(ret) =  <class 'numpy.ndarray'> , ret_val =  [ 8.         15.00000001]


## 예제 2-3.

In [41]:
def func3(w, x, y, z):
    return w*x + x*y*z + 3*w + z*(y**2)

f = lambda W : func3(W[0][1], W[0][1], W[1][0], W[1][1])

W = np.array([[1.0, 2.0], [3.0, 4.0]])

ret = numerical_derivative(f, W)
print('type(ret) = ', type(ret), ', ret_val = ', ret)

debug 1. initial input variable =  [[1. 2.]
 [3. 4.]]
debug 2. initial grad =  [[0. 0.]
 [0. 0.]]
debug 3. idx =  (0, 0) , x[idx] =  1.0
debug 4. grad[idx] =  0.0
debug 5. grad =  [[0. 0.]
 [0. 0.]]
debug 3. idx =  (0, 1) , x[idx] =  2.0
debug 4. grad[idx] =  19.0000000000623
debug 5. grad =  [[ 0. 19.]
 [ 0.  0.]]
debug 3. idx =  (1, 0) , x[idx] =  3.0
debug 4. grad[idx] =  31.999999999996476
debug 5. grad =  [[ 0. 19.]
 [32.  0.]]
debug 3. idx =  (1, 1) , x[idx] =  4.0
debug 4. grad[idx] =  15.000000000000568
debug 5. grad =  [[ 0. 19.]
 [32. 15.]]
type(ret) =  <class 'numpy.ndarray'> , ret_val =  [[ 0. 19.]
 [32. 15.]]


## 예제 2-4.

In [40]:
f = lambda W : func1(W)

W = np.array([3])
ret = numerical_derivative(f, W)
print('type(ret) = ', type(ret), ', ret_val = ', ret)

W = np.array([3.0])
ret = numerical_derivative(f, W)
print('type(ret) = ', type(ret), ', ret_val = ', ret)

debug 1. initial input variable =  [3]
debug 2. initial grad =  [0]
debug 3. idx =  (0,) , x[idx] =  3
debug 4. grad[idx] =  25000
debug 5. grad =  [25000]
type(ret) =  <class 'numpy.ndarray'> , ret_val =  [25000]
debug 1. initial input variable =  [3.]
debug 2. initial grad =  [0.]
debug 3. idx =  (0,) , x[idx] =  3.0
debug 4. grad[idx] =  6.000000000012662
debug 5. grad =  [6.]
type(ret) =  <class 'numpy.ndarray'> , ret_val =  [6.]


# 선형회귀 예제 1

In [1]:
import numpy as np

def numerical_derivative(f, x):
    delta_x = 1e-4 # 0.0001
    grad = np.zeros_like(x)
    
    it = np.nditer(x, flags=['multi_index'], op_flags=['readwrite'])
    
    while not it.finished:
        idx = it.multi_index        
        tmp_val = x[idx]
        x[idx] = float(tmp_val) + delta_x
        fx1 = f(x) # f(x+delta_x)
        
        x[idx] = float(tmp_val) - delta_x 
        fx2 = f(x) # f(x-delta_x)
        grad[idx] = (fx1 - fx2) / (2*delta_x)
        
        x[idx] = tmp_val 
        it.iternext()   
        
    return grad

In [2]:
x_data = np.array([1.0, 2.0, 3.0, 4.0, 5.0]).reshape(5, 1)
t_data = np.array([2.0, 3.0, 4.0, 5.0, 6.0]).reshape(5, 1)

print("x_data.shape = ", x_data.shape, ", t_data.shape = ", t_data.shape)

x_data.shape =  (5, 1) , t_data.shape =  (5, 1)


In [3]:
W = np.random.rand(1, 1)
b = np.random.rand(1)

print("W = ", W, ", W.shape = ", W.shape, ", b = ", b, ", b.shape = ", b.shape)

W =  [[0.68788993]] , W.shape =  (1, 1) , b =  [0.23519016] , b.shape =  (1,)


In [2]:
def loss_func(x, t):
    y = np.dot(x, W) + b
    
    return (np.sum((t - y)**2)) / (len(x))

In [3]:
# 손실함수 값 계산 함수
# 입력변수 x, t : numpy type
def loss_val(x, t):
    y = np.dot(x, W) + b
    
    return (np.sum((t - y)**2)) / (len(x))

# 학습을 마친 후, 임의의 데이터에 대해 미래 값 예측 함수
# 입력변수 x : numpy type

def predict(x):
    y = np.dot(x, W) + b
    
    return y

In [7]:
learning_rate = 1e-2

f = lambda x : loss_func(x_data, t_data)

print("Initial loss value = ", loss_val(x_data, t_data), "Initial W = ", W, "\n", ", b = ", b)

for step in range(8001):
    W -= learning_rate * numerical_derivative(f, W)
    b -= learning_rate * numerical_derivative(f, b)
    
    if (step % 400 == 0):
        print("step = ", step, "loss value = ", loss_val(x_data, t_data), "W = ", W, ", b = ", b)

Initial loss value =  10.181812180980097 Initial W =  [[0.30106418]] 
 , b =  [0.06286786]
step =  0 loss value =  6.028294563952544 W =  [[0.51105799]] , b =  [0.11094702]
step =  400 loss value =  0.006345152260800199 W =  [[1.05172705]] , b =  [0.81329462]
step =  800 loss value =  0.00040485822660676636 W =  [[1.01306617]] , b =  [0.95283854]
step =  1200 loss value =  2.583234836834906e-05 W =  [[1.00330049]] , b =  [0.98808709]
step =  1600 loss value =  1.6482565460428201e-06 W =  [[1.0008337]] , b =  [0.99699082]
step =  2000 loss value =  1.0516851208540502e-07 W =  [[1.00021059]] , b =  [0.99923989]
step =  2400 loss value =  6.710372824450655e-09 W =  [[1.00005319]] , b =  [0.999808]
step =  2800 loss value =  4.2816145774597594e-10 W =  [[1.00001344]] , b =  [0.9999515]
step =  3200 loss value =  2.731923228048877e-11 W =  [[1.00000339]] , b =  [0.99998775]
step =  3600 loss value =  1.7431285311092202e-12 W =  [[1.00000086]] , b =  [0.99999691]
step =  4000 loss value =  1

In [8]:
predict(np.array([500]))

array([501.])

# 선형회귀 예제 2

In [2]:
import numpy as np

def numerical_derivative(f, x):
    delta_x = 1e-4 # 0.0001
    grad = np.zeros_like(x)
    
    it = np.nditer(x, flags=['multi_index'], op_flags=['readwrite'])
    
    while not it.finished:
        idx = it.multi_index        
        tmp_val = x[idx]
        x[idx] = float(tmp_val) + delta_x
        fx1 = f(x) # f(x+delta_x)
        
        x[idx] = float(tmp_val) - delta_x 
        fx2 = f(x) # f(x-delta_x)
        grad[idx] = (fx1 - fx2) / (2*delta_x)
        
        x[idx] = tmp_val 
        it.iternext()   
        
    return grad

In [3]:
loaded_data = np.loadtxt('./data-01.csv', delimiter=',', dtype=np.float32)

print("loaded_data : ", loaded_data, ", loaded_data.shape : ", loaded_data.shape)

x_data = loaded_data[ : , :3]
t_data = loaded_data[ : , 3:4]

print("x_data : ", x_data, ", x_data.shape : ", x_data.shape)
print("t_data : ", t_data, ", t_data.shape : ", t_data.shape)

loaded_data :  [[ 73.  80.  75. 152.]
 [ 93.  88.  93. 185.]
 [ 89.  91.  90. 180.]
 [ 96.  98. 100. 196.]
 [ 73.  66.  70. 142.]
 [ 53.  46.  55. 101.]
 [ 69.  74.  77. 149.]
 [ 47.  56.  60. 115.]
 [ 87.  79.  90. 175.]
 [ 79.  70.  88. 164.]
 [ 69.  70.  73. 141.]
 [ 70.  65.  74. 141.]
 [ 93.  95.  91. 184.]
 [ 79.  80.  73. 152.]
 [ 70.  73.  78. 148.]
 [ 93.  89.  96. 192.]
 [ 78.  75.  68. 147.]
 [ 81.  90.  93. 183.]
 [ 88.  92.  86. 177.]
 [ 78.  83.  77. 159.]
 [ 82.  86.  90. 177.]
 [ 86.  82.  89. 175.]
 [ 78.  83.  85. 175.]
 [ 76.  83.  71. 149.]
 [ 96.  93.  95. 192.]] , loaded_data.shape :  (25, 4)
x_data :  [[ 73.  80.  75.]
 [ 93.  88.  93.]
 [ 89.  91.  90.]
 [ 96.  98. 100.]
 [ 73.  66.  70.]
 [ 53.  46.  55.]
 [ 69.  74.  77.]
 [ 47.  56.  60.]
 [ 87.  79.  90.]
 [ 79.  70.  88.]
 [ 69.  70.  73.]
 [ 70.  65.  74.]
 [ 93.  95.  91.]
 [ 79.  80.  73.]
 [ 70.  73.  78.]
 [ 93.  89.  96.]
 [ 78.  75.  68.]
 [ 81.  90.  93.]
 [ 88.  92.  86.]
 [ 78.  83.  77.]
 [ 82.  

In [4]:
W = np.random.rand(3, 1)
b = np.random.rand(1)

print("W = ", W, ", W.shape = ", W.shape, ", b = ", b, ", b.shape = ", b.shape)

W =  [[0.61360482]
 [0.53389665]
 [0.46287058]] , W.shape =  (3, 1) , b =  [0.67052173] , b.shape =  (1,)


In [5]:
def loss_func(x, t):
    y = np.dot(x, W) + b
    
    return (np.sum((t - y)**2)) / (len(x))

In [6]:
# 손실함수 값 계산 함수
# 입력변수 x, t : numpy type
def loss_val(x, t):
    y = np.dot(x, W) + b
    
    return (np.sum((t - y)**2)) / (len(x))

# 학습을 마친 후, 임의의 데이터에 대해 미래 값 예측 함수
# 입력변수 x : numpy type

def predict(x):
    y = np.dot(x, W) + b
    
    return y

In [8]:
learning_rate = 1e-4

f = lambda x : loss_func(x_data, t_data)

print("Initial loss value = ", loss_val(x_data, t_data), "Initial W = ", W, "\n", ", b = ", b)

for step in range(8001):
    W -= learning_rate * numerical_derivative(f, W)
    b -= learning_rate * numerical_derivative(f, b)
    
    if (step % 1000 == 0):
        print("step = ", step, "loss value = ", loss_val(x_data, t_data))

Initial loss value =  3.5289680625647305e+29 Initial W =  [[-2.77934731e+12]
 [-2.91458394e+12]
 [-1.67641489e+12]] 
 , b =  [1.05579589e+08]
step =  0 loss value =  3.5289680625647305e+29
step =  1000 loss value =  3.5289680625647305e+29
step =  2000 loss value =  3.5289680625647305e+29
step =  3000 loss value =  3.5289680625647305e+29
step =  4000 loss value =  3.5289680625647305e+29
step =  5000 loss value =  3.5289680625647305e+29
step =  6000 loss value =  3.5289680625647305e+29
step =  7000 loss value =  3.5289680625647305e+29
step =  8000 loss value =  3.5289680625647305e+29
