In [1]:
import numpy as np
from datetime import datetime

def numerical_derivative(f, x):
    delta_x = 1e-4 # 0.0001
    grad = np.zeros_like(x)
    
    it = np.nditer(x, flags=['multi_index'], op_flags=['readwrite'])
    
    while not it.finished:
        idx = it.multi_index        
        tmp_val = x[idx]
        x[idx] = float(tmp_val) + delta_x
        fx1 = f(x) # f(x+delta_x)
        
        x[idx] = float(tmp_val) - delta_x 
        fx2 = f(x) # f(x-delta_x)
        grad[idx] = (fx1 - fx2) / (2*delta_x)
        
        x[idx] = tmp_val 
        it.iternext()   
        
    return grad

In [8]:
loaded_data = np.loadtxt('./sps.csv', delimiter=',', dtype=np.float32)

print("loaded_data.shape : ", loaded_data.shape, ", loaded_data : ", loaded_data)

x_data = loaded_data[ : , :-1]
t_data = loaded_data[ : , [-1]]

print("x_data.shape : ", x_data.shape)
print("x_data : ", x_data)
print("t_data.shape : ", t_data.shape)
print("t_data : ", t_data)

loaded_data.shape :  (50, 5) , loaded_data :  [[  1.   1.   1.   2.   1.]
 [ 14.   2.  -3.   9.   0.]
 [  5.   4.   1.   0.  -2.]
 [ -4.   3.   2.   1.   6.]
 [  3.   5.   1.   8.   9.]
 [  3.  -1.   5.   8.  -1.]
 [  2.   2.   3.   7.   4.]
 [  4.   4.   5.   6.   1.]
 [  0.   4.   4.   4.   4.]
 [ -2.   1.   1.   3.   5.]
 [  1.   7.  -2.   1.   9.]
 [  0.   9.   0.   0.   9.]
 [  0.   2.   1.   1.   2.]
 [  0.   3.   3.   3.   3.]
 [-11.   1.   4.  -7.   1.]
 [ -8.   4.   1.  -9.   2.]
 [  5.   2.  -2.   2.   1.]
 [  0.   3.   3.   2.   2.]
 [ -6.   1.   6.   1.   2.]
 [  1.   4.   5.   4.   2.]
 [ -8.   3.   3.  -7.   1.]
 [ 16.   8.  -7.   8.   7.]
 [  0.   1.   2.  -3.  -4.]
 [  0.   0.   0.   0.   0.]
 [  2.  -1.  -2.  -3.  -4.]
 [  2.   5.  -1.   1.   5.]
 [ -4.   3.  -1.  -4.   4.]
 [ -3.   2.   3.   1.   3.]
 [-14.  -9.   5.   1.   1.]
 [  0.   0.   1.   2.   1.]
 [  0.   1.   1.   1.   1.]
 [ -6.   0.   2.   4.   8.]
 [ -7.  -4.  -1.   0.   4.]
 [  4.   3.  -1.  -1.  -1.]
 [

In [3]:
W = np.random.rand(4, 1)
b = np.random.rand(1)

print("W = ", W, ", W.shape = ", W.shape, ", b = ", b, ", b.shape = ", b.shape)

W =  [[0.51409097]
 [0.67521255]
 [0.48936476]
 [0.76110766]] , W.shape =  (4, 1) , b =  [0.96627492] , b.shape =  (1,)


In [4]:
def loss_func(x, t):
    y = np.dot(x, W) + b
    
    return (np.sum((t - y)**2)) / (len(x))

In [5]:
# 손실함수 값 계산 함수
# 입력변수 x, t : numpy type
def loss_val(x, t):
    y = np.dot(x, W) + b
    
    return (np.sum((t - y)**2)) / (len(x))

# 학습을 마친 후, 임의의 데이터에 대해 미래 값 예측 함수
# 입력변수 x : numpy type

def predict(x):
    y = np.dot(x, W) + b
    
    return y

In [6]:
learning_rate = 1e-3

f = lambda x : loss_func(x_data, t_data)

start_time = datetime.now()

for step in range(30001):
    W -= learning_rate * numerical_derivative(f, W)
    b -= learning_rate * numerical_derivative(f, b)
    
    if step % 2000 == 0:
        print("step = ", step, "loss value = ", loss_val(x_data, t_data))
        
end_time = datetime.now()

print("")
print("Elapsed Time => ", end_time - start_time)

step =  0 loss value =  44.59236617724355
step =  2000 loss value =  0.007872483587380637
step =  4000 loss value =  0.00011765986035764536
step =  6000 loss value =  1.758510433640224e-06
step =  8000 loss value =  2.628219118939968e-08
step =  10000 loss value =  3.928060706973274e-10
step =  12000 loss value =  5.8707665621054664e-12
step =  14000 loss value =  8.774278865463745e-14
step =  16000 loss value =  1.3113784979908629e-15
step =  18000 loss value =  1.9599489489969433e-17
step =  20000 loss value =  2.929282815028647e-19
step =  22000 loss value =  4.378129602244987e-21
step =  24000 loss value =  6.548002742688209e-23
step =  26000 loss value =  9.84977579027694e-25
step =  28000 loss value =  1.6570449851651338e-26
step =  30000 loss value =  1.019235043343982e-27

Elapsed Time =>  0:00:16.338809


In [7]:
import matplotlib.pyplot as plt

%matplotlib inline

x = [step for step in range(30001)]
y = [loss_value for loss_value in loss_val(x_data, t_data)]

plt.title('Loss Value Trend')
plt.grid()
plt.plot(x, y, color='b')
plt.show()

TypeError: 'numpy.float64' object is not iterable

In [7]:
print(predict(np.array([4, 4, 4, 4])))
print(predict(np.array([-3, 0, 9, 1])))

[-2.17530966e-14]
[-5.]


In [1]:
import numpy as np
from datetime import datetime
import matplotlib.pyplot as plt

class LinearRegressionTest:
    def __init__(self, loading_data, learning_rate, iteration_count):
        self.loading_data =  np.loadtxt('./{}'.format(loading_data), delimiter=',', dtype=np.float32)
        self.x_data = self.loading_data[ : , :-1]
        self.t_data = self.loading_data[ : , [-1]]
        
        self.learning_rate = learning_rate
        self.iteration_count = iteration_count
        
        self.W = np.random.rand(4, 1)
        self.b = np.random.rand(1)
        
    def loss_func(self, x, t):
        y = np.dot(x, self.W) + self.b
    
        return (np.sum((t - y)**2)) / (len(x))
    
    # 손실함수 값 계산 함수
    # 입력변수 x, t : numpy type
    def loss_val(self, x, t):
        y = np.dot(x, self.W) + self.b
    
        return (np.sum((t - y)**2)) / (len(x))

    def numerical_derivative(self, f, x):
        delta_x = 1e-4 # 0.0001
        grad = np.zeros_like(x)
    
        it = np.nditer(x, flags=['multi_index'], op_flags=['readwrite'])
    
        while not it.finished:
            idx = it.multi_index        
            tmp_val = x[idx]
            x[idx] = float(tmp_val) + delta_x
            fx1 = f(x) # f(x+delta_x)
        
            x[idx] = float(tmp_val) - delta_x 
            fx2 = f(x) # f(x-delta_x)
            grad[idx] = (fx1 - fx2) / (2*delta_x)
        
            x[idx] = tmp_val 
            it.iternext()   
        
        return grad

    def train(self):
        f = lambda x : self.loss_func(self.x_data, self.t_data)

        start_time = datetime.now()

        for step in range(self.iteration_count):
            self.W -= self.learning_rate * self.numerical_derivative(f, self.W)
            self.b -= self.learning_rate * self.numerical_derivative(f, self.b)
    
            if step % 2000 == 0:
                print("step = ", step, "loss value = ", self.loss_val(self.x_data, self.t_data))
        
        end_time = datetime.now()

        print("")
        print("Elapsed Time => ", end_time - start_time)
    
    # 학습을 마친 후, 임의의 데이터에 대해 미래 값 예측 함수
    # 입력변수 x : numpy type
    def predict(self, x):
        y = np.dot(x, self.W) + self.b
    
        return y
        

In [2]:
obj = LinearRegressionTest('sps.csv', 1e-3, 30001)
obj.train()

step =  0 loss value =  26.457271065054456
step =  2000 loss value =  0.0009416293736654389
step =  4000 loss value =  1.4073312961241292e-05
step =  6000 loss value =  2.1033568799788154e-07
step =  8000 loss value =  3.1436166997702267e-09
step =  10000 loss value =  4.698359108792314e-11
step =  12000 loss value =  7.022032405146715e-13
step =  14000 loss value =  1.049492768343949e-14
step =  16000 loss value =  1.5685417745497062e-16
step =  18000 loss value =  2.344297793129772e-18
step =  20000 loss value =  3.5037296551263675e-20
step =  22000 loss value =  5.237402001440397e-22
step =  24000 loss value =  7.851398474097048e-24
step =  26000 loss value =  1.2048273967866076e-25
step =  28000 loss value =  2.9836160084866556e-27
step =  30000 loss value =  6.379052129681757e-28

Elapsed Time =>  0:00:15.244760
